CL = clisp
D = day
use:
	@echo Usage:  make '#day'

1: $(D)1/$(D)1.lisp
	$(CL) $(D)1/$(D)1.lisp

2: $(D)2/$(D)2.lisp
	$(CL) $(D)2/$(D)2.lisp

3: $(D)3/$(D)3.lisp
	$(CL) $(D)3/$(D)3.lisp

4: $(D)4/$(D)4.lisp
	$(CL) $(D)4/$(D)4.lisp

5: $(D)5/$(D)5.lisp
	$(CL) $(D)5/$(D)5.lisp

6: $(D)6/$(D)6.lisp
	$(CL) $(D)6/$(D)6.lisp

7: $(D)7/$(D)7.lisp
	$(CL) $(D)7/$(D)7.lisp

8: $(D)8/$(D)8.lisp
	$(CL) $(D)8/$(D)8.lisp
